### ISSUE TITLE
Store data in local storage

### ISSUE THREAD

**Issue by eMerzh** [betagouv/ecolab-climat#79]
Hi, 

found the project really fun, and interesting to see what's the order of magnitude between two things (like transport vs food).

But when you come back to the form to check what you can do to help, what's YOUR easiest way to do impactful things, 
you have to do the form again and again....

It would be really cool to save the state of the form in local storage so that we can iterate on it, and reload it if there's a revisit....

Would you be open to something like that?

**Comment by laem** [comment]
Hi, what you're describing is already in place. If it's not, it's a bug 😅 
The button is called "Ma dernière simulation". 

By the way, can you read french ? Would you be interested in translating / internationalizing the data model :) ?

**Comment by eMerzh** [comment]
oh 😮 .... can't find the button 🤔 ...
Tried chrome and Firefox ... no success
I can read French I live in Belgium :p, so not a native either, but I might be able to help for the translation of the DM or the commens here and there :)

**Comment by eMerzh** [comment]
ok it seems to be there now... strange, i did it a couple of times... 

for the translation, where should that take place? in the data- repo?

**Comment by laem** [comment]
> for the translation, where should that take place? in the data- repo?

Good question. This project is a fork from betagouv/mon-entreprise, which is completely translated, UI and rules. The UI is translated with the standard react-i18next and the rules with custom code. 

Since the fork, mon-entreprise dit separate the publicodes package from the UI. I'll soon do the same here, and we should get a better working base for translation :)
